name: Build Civil3D Plugin

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore packages (none required)
      run: echo "No NuGet packages to restore"

    - name: Build project
      run: msbuild SurfaceCorrectionPlugin/SurfaceCorrectionPlugin.csproj /p:Configuration=Release

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v3
      with:
        name: SurfaceCorrectionPlugin
        path: SurfaceCorrectionPlugin\bin\Release\SurfaceCorrectionPlugin.dll